FROM mcr.microsoft.com/devcontainers/go:1.21-bullseye

# the `cargo generate` command accused that $USER was missing
ENV USER=root

RUN apt-get update

# installing bat, 'cause it's fun :D
RUN apt-get install wget -y
RUN wget -P /tmp https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb
RUN dpkg -i /tmp/bat_0.12.1_amd64.deb

# istalling The Silver Searcher 'cause it's awesome
RUN apt-get install silversearcher-ag

# installing kind for Kubernetes
RUN go install sigs.k8s.io/kind@v0.20.0
